
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 24 2026 12:30:59 IST (Feb 24 2026 07:00:59 UTC)

// Verification Directory fv/alu 

module alu(A, B, sel, result);
  input [3:0] A, B;
  input [2:0] sel;
  output [3:0] result;
  wire [3:0] A, B;
  wire [2:0] sel;
  wire [3:0] result;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_18, n_19, n_20, n_21, n_22, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_36;
  AO21X2 g794__2398(.A0 (n_15), .A1 (n_34), .B0 (n_36), .Y (result[3]));
  OAI21XL g795__5107(.A0 (n_31), .A1 (n_2), .B0 (n_33), .Y (n_36));
  AO21X2 g796__6260(.A0 (n_0), .A1 (n_34), .B0 (n_32), .Y (result[2]));
  AOI32XL g797__4319(.A0 (n_28), .A1 (B[3]), .A2 (A[3]), .B0 (n_30),
       .B1 (n_27), .Y (n_33));
  OAI21XL g798__8428(.A0 (n_31), .A1 (n_4), .B0 (n_29), .Y (n_32));
  OAI21XL g799__5526(.A0 (n_24), .A1 (n_25), .B0 (n_26), .Y (n_30));
  AOI32XL g800__6783(.A0 (n_28), .A1 (B[2]), .A2 (A[2]), .B0 (n_22),
       .B1 (n_27), .Y (n_29));
  NAND2XL g801__3680(.A (n_25), .B (n_24), .Y (n_26));
  AO21X2 g802__1617(.A0 (n_1), .A1 (n_34), .B0 (n_21), .Y (result[1]));
  ADDFX1 g803__2802(.A (n_13), .B (A[2]), .CI (n_18), .CO (n_24), .S
       (n_22));
  OAI21XL g804__1705(.A0 (n_31), .A1 (n_5), .B0 (n_20), .Y (n_21));
  AOI32XL g805__5122(.A0 (n_28), .A1 (B[1]), .A2 (A[1]), .B0 (n_19),
       .B1 (n_27), .Y (n_20));
  ADDFX1 g806__8246(.A (n_8), .B (A[1]), .CI (n_11), .CO (n_18), .S
       (n_19));
  OAI21X4 g807__7098(.A0 (n_3), .A1 (n_31), .B0 (n_16), .Y (result[0]));
  AOI222XL g808__6131(.A0 (n_7), .A1 (n_28), .B0 (n_27), .B1 (n_10),
       .C0 (n_34), .C1 (n_9), .Y (n_16));
  MXI2XL g810__1881(.A (A[3]), .B (n_15), .S0 (n_14), .Y (n_25));
  MXI2XL g816__5115(.A (n_12), .B (sel[0]), .S0 (B[3]), .Y (n_14));
  MXI2XL g817__7482(.A (n_12), .B (sel[0]), .S0 (B[2]), .Y (n_13));
  OAI21XL g809__4733(.A0 (n_12), .A1 (B[0]), .B0 (n_6), .Y (n_11));
  MXI2XL g812__6161(.A (n_9), .B (A[0]), .S0 (B[0]), .Y (n_10));
  MXI2XL g815__9315(.A (n_12), .B (sel[0]), .S0 (B[1]), .Y (n_8));
  NAND2XL g814__9945(.A (sel[0]), .B (n_28), .Y (n_31));
  INVXL g811(.A (n_6), .Y (n_7));
  NOR3BXL g813__2883(.AN (sel[2]), .B (sel[0]), .C (sel[1]), .Y (n_34));
  NOR2XL g818__2346(.A (A[1]), .B (B[1]), .Y (n_5));
  NOR2XL g819__1666(.A (sel[2]), .B (sel[1]), .Y (n_27));
  NOR2BXL g820__7410(.AN (sel[1]), .B (sel[2]), .Y (n_28));
  NOR2XL g823__6417(.A (A[2]), .B (B[2]), .Y (n_4));
  NOR2XL g821__5477(.A (A[0]), .B (B[0]), .Y (n_3));
  NOR2XL g822__2398(.A (A[3]), .B (B[3]), .Y (n_2));
  NAND2XL g824__5107(.A (B[0]), .B (A[0]), .Y (n_6));
  INVXL g825(.A (A[1]), .Y (n_1));
  INVXL g827(.A (A[3]), .Y (n_15));
  INVXL g826(.A (A[2]), .Y (n_0));
  INVXL g828(.A (A[0]), .Y (n_9));
  INVXL g829(.A (sel[0]), .Y (n_12));
endmodule

